### PR TITLE
Make the get and set method of the `geomagicdriver` device non-blocking, similar to te rest of existing YARP devices.

### PR DESCRIPTION
**Pull request by traversaro**
Related issue: https://github.com/robotology/haptic-devices/issues/10 .

### CODE REVIEW

**Comment by traversaro** [comment]
@prajval10 if you could test on your system, this should solve the problem of the ~2 ms necessary to read the Geomagic data .

**Comment by traversaro** [comment]
cc @pattacini

**Review by pattacini — APPROVED** [review]

**Comment by prajval10** [comment]
@traversaro it fixed the 2ms issue:
```
---------------------------------
duration_read: 9476 us
duration_geomagic: 11 us
duration_filter: 0 us
duration_write: 84 us
---------------------------------
duration_read: 9372 us
duration_geomagic: 11 us
duration_filter: 0 us
duration_write: 87 us
---------------------------------
duration_read: 9574 us
duration_geomagic: 12 us
duration_filter: 1 us
duration_write: 113 us
---------------------------------
duration_read: 11364 us
duration_geomagic: 11 us
duration_filter: 0 us
duration_write: 80 us
---------------------------------
```

**Review by prajval10 — APPROVED** [review]

**Comment by traversaro** [comment]
Great! Merging.

**Pull request merged**
